### ISSUE TITLE
Relaton "published" code changed to "approved"

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-ogc#12]
https://github.com/metanorma/metanorma-ogc/issues/196

**Comment by opoudjis** [comment]
I am going to put a mitigation in place, but this needs to be consistent with metanorma.

**Comment by andrew2net** [comment]
@opoudjis we don't have any stage constraint. Maybe you mean date type, do you?
All date-type constraints are in the relaton-bib. Should we change the constrains in the relaton-bib or make an alternative in the relaton-ogc?

**Comment by opoudjis** [comment]
No, I meant stage. If you don't represent stage for published documents (i.e. you don't populate `<status><stage/></status>`), then there is nothing here for you to do.

**Comment by andrew2net** [comment]
The stage can contain any text:
```
stage = element stage { 
  attribute abbreviation { text }?,
  text
}
```
