### ISSUE TITLE
Move data to relaton-data-ogc

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-ogc#16]
In case using relaton as an API, it's run in an AWS Lambda container. Lambda has a read-only file system and doesn't allow saving files. The relaton-ogc gem fetches and saves the data file with documents.
We need to parse the data file and save the documents as separated files in the GitHub relaton-data-ogc repository.
@ronaldtse do you agree?

**Comment by ronaldtse** [comment]
Agree, OGC has given us permission to make this information available to the public as long as we keep the information up to date.

**Comment by ronaldtse** [comment]
But as a note, the lambda can utilize S3 as well. We could potentially keep Relaton-data-* synchronized with S3 via GitHub actions

**Comment by andrew2net** [comment]
Do you mean we should store documents in S3 instead of GitHub repos? It will cost some money. On the other side getting documents from a GitHub repo is fast enough. Do we have reasons to do it?

**Comment by ronaldtse** [comment]
@andrew2net for the API we wish to have a "contained deployment" so that it is not linked with GitHub repositories. That's why it makes more sense to have the GitHub repository contents uploaded to S3 for the purpose of the API which can see heavy use.

**Comment by andrew2net** [comment]
@ronaldtse 

> for the API we wish to have a "contained deployment" so that it is not linked with GitHub repositories.

We already have `relaton-data-*` repositories like `relaton-data-iho`, `relaton-data-bipm` etc. It isn't a problem to fetch the data from a GH repository in a container. I see only one advantage in storing data on S3. It may work faster than fetching from GH.
Should we move all the `relaton-data-*` repositories to S3?

**Comment by ronaldtse** [comment]
> I see only one advantage in storing data on S3. It may work faster than fetching from GH.

Exactly, it **should** work faster, and the "contained" aspect is also very important because this allows "near-edge" by serving from the same region, theoretically.

> Should we move all the relaton-data-* repositories to S3?

We should keep these separate, because the relaton-data-* repositories are consider the "golden copies", and provides us with confidence that data is correct. We should have one S3 bucket mirror all the relaton-data-* repositories.

**Comment by andrew2net** [comment]
@phuonghuynh we need to create a new `relaton-data` bucket for storing `relaton-data-*` files.

**Comment by andrew2net** [comment]
@ronaldtse do you mean we should fetch data from S3 in `api.relaton.org` and from GH in `relaton-ogc` gem?

**Comment by phuonghuynh** [comment]
@andrew2net we need to update permission and add new ENV to access new bucket for Lambda Role. Which env-name you are using for this?

**Comment by ronaldtse** [comment]
> @ronaldtse do you mean we should fetch data from S3 in `api.relaton.org` and from GH in `relaton-ogc` gem?

Yes.

> @andrew2net we need to update permission and add new ENV to access new bucket for Lambda Role. Which env-name you are using for this?

Why can't we just use the current ENVs? We need production + staging.

e.g. we can call it `relaton-api-data-{env}`?

**Comment by phuonghuynh** [comment]
I am not sure, look like we already have a S3 ENV name for lambda access. Look like Andrew need a new one for new API features?
@andrew2net

**Comment by andrew2net** [comment]
@ronaldtse there are duplicates in the [dataset](https://raw.githubusercontent.com/opengeospatial/NamingAuthority/master/incubation/bibliography/bibliography.json). The duplicated codes are: `09-000`, `07-036`, `12-006`, `11-122r1`. These duplicates have the same URL or absence of URL.
It looks like an error. Shouldn't we notify OGC about it?

**Comment by ronaldtse** [comment]
Data issues moved to relaton/relaton-data-ogc#1

**Comment by ronaldtse** [comment]
But this is not a blocker to implementation, we can just take the first one of two duplicates right now.
