### ISSUE TITLE
(URGENT) Some recent OGC documents have not been imported into relaton

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ogc#19]
@ghobona reported:

Some recent OGC documents have not been imported into relaton.

_Originally posted by @ronaldtse in https://github.com/relaton/relaton-data-ogc/issues/2#issuecomment-1107790827_

**Comment by ghobona** [comment]
Specifically, this document does not appear to be in relaton. https://docs.ogc.org/is/18-062r2/18-062r2.html

**Comment by ronaldtse** [comment]
@ghobona I'm also not seeing OGC 08-134...

**Comment by gbuehler** [comment]
I have updated the credentials on the git commit.  The entire catalog should not be updated and remain so.

**Comment by ronaldtse** [comment]
Confirm that this is fixed. Thank you @gbuehler !
