### ISSUE TITLE
Confirm support of OGC document types

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ogc#2]
@andrew2net can you help confirm that we now support all these document types? Can you add them to documentation? Thanks!

AS => Abstract Specification
BP => Best Practice
CAN => Candidate Standard
CC => Conformance Class
CR => Change Request
CS => Community Standard
CP => Community Practice
DP => Discussion Paper
DP-Draft => Draft Discussion Paper
IPR => Interoperability Program Report-Engineering Specification
IS => Implementation Standard
ISC => Implementation Standard Corrigendum
ISx => Extension Package Standard
Notes => Notes
ORM => OGC Reference Model
PC => Profile Corrigendum
PER => Public Engineering Report
POL => Policy
POL-NTS => Policy - Name Type Specification
Primer => Primer
Profile => Profile
RFC => Request for Comment
Retired => Retired document
SAP => Standard Application Profile
TS => Test Suite
WhitePaper => Whitepaper

**Comment by andrew2net** [comment]
@ronaldtse we support all of then except CP. I'll add it. POL-NTS is presented in JSON as POLNTS.
I've just checked the lastest JSON. There are additional types in it:
```
 "ATB"
 "P"
 "Praft"
 "RP"
```
How should we treat them?

@opoudjis in the `ogc.rng` we have:
```
    <define name="DocumentType">
      <choice>
        <value>standard</value>
        <value>standard-with-suite</value>
        <value>abstract-specification</value>
        <value>community-standard</value>
        <value>profile</value>
        <value>best-practice</value>
        <value>engineering-report</value>
        <value>discussion-paper</value>
        <value>reference-model</value>
        <value>user-guide</value>
        <value>policy</value>
        <value>guide</value>
        <value>amendment</value>
        <value>technical-corrigendum</value>
        <value>administrative</value>
      </choice>
    </define>
```
shouldn't we fix the list of allowed types?

**Comment by ronaldtse** [comment]
I've just sought for clarification from OGC, will reply.

**Comment by ronaldtse** [comment]
@andrew2net can you let me know which exact documents have those types? Thanks.

**Comment by opoudjis** [comment]
Andrej, yes, and this is the first I've seen this list of types. I'm assuming we want to use the abbreviations rather than the fully spelled out version? We will need to update metanorma.com documentation as well.

@ronaldtse please advise as to spelled out vs abbreviated, but spelled out is what they have already been told to use in metanorma-ogc.

**Comment by andrew2net** [comment]
> @andrew2net can you let me know which exact documents have those types? Thanks.

`P` and `Praft` were my mistakes. Sorry.  I found 2 `ATB` documents:
```
{"899"=>
  {"title"=>"OGC Technical Document Baseline",
   ...
   "identifier"=>"04-014r1",
   "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=5393",
   "type"=>"D-ATB",
   ...},
 "936"=>
  {"title"=>"OGC Technical Document Baseline",
  ...
   "identifier"=>"03-053r1",
   "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=3835",
   "type"=>"D-ATB",
  ...}}
```
And 13 `RP` documents:
```
{"888"=>
  {"title"=>"Sensor Model Language (SensorML) for In-situ and Remote Sensors",
  ...
  "identifier"=>"04-019r2",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=7927",
  "type"=>"D-RP",
  ...},
 "900"=>
  {"title"=>"GO-1 Application Objects",
  ...
  "identifier"=>"03-064r5",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=5936",
  ...
  "type"=>"D-RP",
  ...},
 "901"=>
  {"title"=>"OWS Common Recomendation Paper",
  ...
  "identifier"=>"04-016r3",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=6324",
  "type"=>"D-RP",
  ...},
 "906"=>
  {"title"=>"Web Map Service",
  ...
  "identifier"=>"03-109r1",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=4756",
  "type"=>"D-RP",
  ...},
 "907"=>
  {"title"=>"OGC Web Services Common",
  ...
  "identifier"=>"03-088r6",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=4550",
  "type"=>"D-RP"
  ...},
 "911"=>
  {"title"=>"Recommended XML Encoding of CRS Definitions",
  ...
  "identifier"=>"03-010r9",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=11517",
  "type"=>"D-RP"
  ...},
 "914"=>
  {"title"=>"Observations and Measurements",
  ...
  "identifier"=>"03-022r3",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=1324",
  "type"=>"D-RP"
  ...},
 "930"=>
  {"title"=>"Recommended XML Encoding of CRS Definitions",
  ...
  "identifier"=>"03-010r7",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=1345",
  "type"=>"D-RP"
  ...},
 "943"=>
  {"title"=>"CT Definition Data for Coordinate Reference",
  ...
  "identifier"=>"01-014r5",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=1012",
  "type"=>"D-RP"
  ...},
 "959"=>
  {"title"=>"Geography Markup Language",
  ...
  "identifier"=>"00-029",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=7197",
  "type"=>"D-RP"
  ...},
 "962"=>
  {"title"=>"Web Map Context Documents",
  ...
  "identifier"=>"02-066r1",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=1181",
  "type"=>"D-RP"
  ...},
 "974"=>
  {"title"=>"Web Coverage Service",
  ...
  "identifier"=>"02-024",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=1131",
  "type"=>"D-RP"
  ...},
 "975"=>
  {"title"=>"Geography Markup Language",
  ...
  "identifier"=>"01-029",
  "URL"=>"https://portal.opengeospatial.org/files/?artifact_id=1034",
  "type"=>"D-RP"
  ...}}
```

**Comment by ronaldtse** [comment]
Official answer from OGC:
ATB  = Approved Technical Baseline
RP    = Recommendation Paper

These are deprecated document types.

**Comment by ronaldtse** [comment]
> please advise as to spelled out vs abbreviated, but spelled out is what they have already been told to use in metanorma-ogc.

We should use the spelled out ones in MN for clarity.

**Comment by opoudjis** [comment]
@andrew2net And because the grammar is the same for bibdata under Relaton and Metanorma (right?), that mean you need the spelled out document types in relaton-ogc as well.

**Comment by opoudjis** [comment]
````
DocumentType =
"abstract-specification" | "best-practice" | "candidate-standard" | "conformance-class" | "change-request" | "community-standard" | "discussion-paper" | "draft-discussion-paper" | "interoperability-program-report" | "implementation-standard" | "implementation-standard-corrigendum" | "extension-package-standard" | "notes" | "ogc-reference-model" | "profile-corrigendum" | "public-engineering-report" | "policy" | "policy-name-type=specification" | "primer" | "profle" | "request-for-comment" | "retired" | "standard-application-profile" | "test-suite" | "whitepaper" | "approved-technical-baseline" | "recommendation-paper"
````

**Comment by opoudjis** [comment]
My further work is at https://github.com/metanorma/metanorma-ogc/issues/54

**Comment by ronaldtse** [comment]
In case it wasn't clear before:

> The “D-“ prefix in the type attribute means that the document is deprecated.

**Comment by andrew2net** [comment]
fixed by 6d6e4e261c46f4a7ab2df274dd96350b27f2cf93

**Comment by ronaldtse** [comment]
@andrew2net does relaton-ogc now support "Community Practice" / "CP"?

**Comment by andrew2net** [comment]
@ronaldtse yes, it has the community-practice type of document.
