### ISSUE TITLE
(URGENT) New location for OGC bibliographic information

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ogc#24]
As mentioned by @ghobona and @gbuehler the OGC bibliographic location has changed. 

https://github.com/opengeospatial/NamingAuthority/commit/d8959b041a1d6918042302aebe15a51b65f7e869#commitcomment-130954986

@andrew2net can you please help double check and update if necessary? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse the new location is exactly the same as it is in relaton-ogc DataFetcher. I've double checked and didn't see any differences.
The new location is https://raw.githubusercontent.com/opengeospatial/NamingAuthority/master/definitions/docs/docs.json
In the Datafetcher it is identical https://github.com/relaton/relaton-ogc/blob/ddd37517182f44e19beb2cbd0b650ad7faf3afab/lib/relaton_ogc/data_fetcher.rb#L6
It looks like the `definitions/docs/docs.json` was a symbolic link to the `incubation/bibliography/bibliography.json` and in the commit they removed the `bibliography.json` and moved all the data to the `docs.json`. So no changes are needed on our side.

**Comment by ghobona** [comment]
That's great! Thanks for confirming.

**Comment by ronaldtse** [comment]
Thanks!
