### ISSUE TITLE
URGENT: Crashing on "OGC 07-036"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ogc#4]
```adoc
* [[[OGC07-036,OGC 07-036]]], Geography Markup Language (aka ISO 19136:2007) (2007)
```

```sh
fetching OGC 07-036...
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.5/bin/metanorma)
ArgumentError: invalid doctype: implementation-standard-corrigendum
```

@andrew2net and Relaton should NEVER crash. Throw errors and display warnings, but NEVER CRASH.

**Comment by andrew2net** [comment]
@ronaldtse Metanorma uses the old version of Relaton. This issue is fixed in the last version. Nick plans to release Metanorma with the last Relaton at the end of next week.

**Comment by ronaldtse** [comment]
@andrew2net I think there is an issue we have with OGC synchronization.

1. There is a new set of "document types" and "subtypes". These are NEW.
2. There is a new set of "document stages". These are NEW.
3. There is a mapping between the OGC bibliography endpoint of document types to our current document types.
4. We need to create a mapping between the OGC bibliography endpoint to the NEW set of document types and subtypes, and they also involve the NEW stages.

Items 1 and 2 affect both Metanorma and Relaton.

Items 3 and 4 affect Relaton only.

This means that Relaton needs to support the NEW document types / subtypes and the NEW document stages, and also the translation of the OLD to NEW.

Metanorma only needs to support the NEW document types / subtypes and the NEW document stages.

**Comment by ronaldtse** [comment]
Ping @opoudjis

**Comment by opoudjis** [comment]
Confirmed fixed, although I needed to update relaton_iev to be able to upgrade to major version of relaton. Will release tonight.
