### ISSUE TITLE
Support OGC NEW document types / subtypes and NEW document stages

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ogc#5]
@andrew2net @opoudjis There is an issue we have with OGC synchronization.

1. There is a new set of "document types" and "subtypes". These are NEW.
2. There is a new set of "document stages". These are NEW.
3. There is a mapping between the OGC bibliography endpoint of document types to our current document types.
4. We need to create a mapping between the OGC bibliography endpoint to the NEW set of document types and subtypes, and they also involve the NEW stages.

Items 1 and 2 affect both Metanorma and Relaton.

Items 3 and 4 affect Relaton only.

This means that Relaton needs to support the NEW document types / subtypes and the NEW document stages, and also the translation of the OLD to NEW.

Metanorma only needs to support the NEW document types / subtypes and the NEW document stages.

NEW document type and subtypes + old document type to new document type mapping:
https://github.com/metanorma/metanorma-ogc/issues/58

NEW document stages:
https://github.com/metanorma/metanorma-ogc/issues/57

**Comment by ronaldtse** [comment]
CC: @ogcscotts @gbuehler @ghobona

**Comment by ronaldtse** [comment]
@andrew2net this has become necessary to implement since Metanorma-OGC needs to support 1 and 2.

**Comment by andrew2net** [comment]
> - approved-technical-baseline => Not a document type, remove.

@ronaldtse but the [json](https://raw.githubusercontent.com/opengeospatial/NamingAuthority/master/incubation/bibliography/bibliography.json) still contains "D-ATB" type. How should we handle it?

**Comment by ronaldtse** [comment]
Let's mark it as "others"?

**Comment by andrew2net** [comment]
@ronaldtse I have no objection

**Comment by andrew2net** [comment]
> - candidate-standard => (standard, in draft stage)

@ronaldtse which subtype should be in this case?

**Comment by ronaldtse** [comment]
Just the default subtype please, since we don't know which each of one are.

**Comment by andrew2net** [comment]
Do you mean to use `null` as default subtype fo `standard`? [Here](https://github.com/metanorma/metanorma-ogc/issues/58#issue-536161047) there is a default subtype for `best practice` only.

**Comment by andrew2net** [comment]
> - implementation-standard-corrigendum => (standard: implementation, with corrigendum)

what does `with corrigendum` mean?

**Comment by ronaldtse** [comment]
> Do you mean to use null as default subtype fo standard? Here there is a default subtype for best practice only.

Let's use "general".

> what does `with corrigendum` mean?

Just ignore `with corrigendum` for now.

**Comment by andrew2net** [comment]
> - policy => (standard: policy)

is the "policy" subtype? There isn't "policy" in the subtypes list.
