### ISSUE TITLE
Does relaton-ogc now support "Community Practice" / "CP"?

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ogc#6]
@andrew2net does relaton-ogc now support "Community Practice" / "CP"?

The Metanorma part has been implemented here: https://github.com/metanorma/metanorma-ogc/issues/54

As described this is a new document type with nothing published yet, so this cannot be fetched right now. However, it still means we need to support it.

_Originally posted by @ronaldtse in https://github.com/relaton/relaton-ogc/issues/2#issuecomment-573472516_

**Comment by andrew2net** [comment]
@ronaldtse I don't see any reason why this gem shouldn't fetch CP documents. We need any published CP document to check it.
