### ISSUE TITLE
Inconsistency in fetching display

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ogc#8]
e.g. 
```
[relaton-iso] ("ISO 8601") fetching...
[relaton-iso] ("ISO 8601") found ISO 8601:2004
fetching OGC 10-004r3...
fetching OGC 08-015r2...
fetching OGC 07-011...
fetching OGC 01-111...
```

Relaton-OGC should follow the Relaton-ISO format. In fact, all relaton flavors should share the same format. Can we get this implemented in main Relaton?

**Comment by andrew2net** [comment]
fixed by https://github.com/relaton/relaton-cli/commit/4e9a1debbf5bf130c6d9d8f31037f53254648d41
